name: SkyBlockSystem
version: 1.0
main: de.cdnrelaxo.skyblocksystem.SkyBlockSystem
description: SkyBlockSystem
authors:
    - CodingRelaxo
api-version: 1.19

depend:
    - ProtocolLib
    - FastAsyncWorldEdit

commands:
    setup:
